name: Electron Forge Build and Publish

on:
    push:
        branches:
          - master


jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        platform: [darwin, win32, linux]

    steps:
    - name: Check ACCESS_TOKEN presence
      run: |
        echo "Checking if ACCESS_TOKEN can be accessed...${{ secrets.ACCESS_TOKEN }}"
        if [ -z "${{ secrets.ACCESS_TOKEN }}" ]; then
        echo "ACCESS_TOKEN is not set or empty."
        exit 1
        else
        echo "ACCESS_TOKEN is set and accessible."
        # 这里可以执行一些不涉及打印Secrets值的操作，比如发起一个HTTP请求验证Token有效性
        # 注意：实际操作中应避免直接在日志中暴露任何敏感信息
        fi
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Authenticate with GitHub
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > .npmrc

    - name: Configure Electron Forge for ${{ matrix.platform }}
      run: |
        echo "ELECTRON_FORGE_MAKER_PLATFORMS=${{ matrix.platform }}" >> $GITHUB_ENV

    - name: Build and Publish with Electron Forge
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: npm run publish